#!/usr/bin/env groovy

boolean success = true
def dockerRegistry = "registry.open-sys.org"

properties([
    disableConcurrentBuilds()
])

try {
    node {
        stage('Checkout') {
            checkout([
                $class: 'GitSCM',
                branches: scm.branches,
                extensions: scm.extensions + [
                    [$class: 'CleanBeforeCheckout'],
                    [$class: 'PathRestriction', excludedRegions: '', includedRegions: '^RMQ/docker/rabbitmq/.*$']
                ],
                submoduleCfg: [],
                userRemoteConfigs: [
                    [credentialsId: 'jenkins-azot-with-key', url: 'git@github.com:caliber223/jenkins_test3.git']
                ]
            ])

            shortCommit = sh(returnStdout: true, script: 'git rev-parse HEAD').trim().take(7)
            currentBuild.description = "${shortCommit}"
            sh 'env | sort'
        }

        dir('RMQ/docker/rabbitmq') {
            stage('Build') {
                sh 'make docker'
            }

            stage('Push') {
                sh 'make push'
                sh 'make push TAG=latest'
            }
        } // end 'dir'

    } // end node 'docker'
} catch (e) {
    echo e.toString()
    sucess = false
    currentBuild.result = 'FAILURE'
} finally {
}
